# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=640)),
                ('sender', models.CharField(max_length=50)),
                ('receive_date', models.DateTimeField(verbose_name='date received')),
            ],
        ),
    ]
